### ISSUE TITLE
Using declarations ICE

### ISSUE THREAD

**Issue by cjdb** [saarraz/clang-concepts-old#21] opened 2018-10-12 21:01 UTC
`using`-declarations on concepts unequivocally cause the compiler to crash.

Minimal repro: https://godbolt.org/z/h275qB

```cpp
namespace foo {
    template<class I>
    concept Integral = true;
} // namespace foo

using foo::Integral;
```

**Comment by saarraz** [comment] 2018-11-05 22:22
Duplicate of #18

**Closed as completed by saarraz** 2018-11-05 22:22 UTC
Labels: duplicate
