### ISSUE TITLE
Behavior difference vs. Godbolt clang-concepts

### ISSUE THREAD

**Issue by CaseyCarter** [saarraz/clang-concepts-old#35] opened 2018-11-18 22:39 UTC
I have a negative test (it's supposed to fail to compile) to detect https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67225 (using deduction constraints in the program "turns off" access control):
```c++
template <class, class>
concept C1 = true;

template <class>
concept C2 = requires { { 42 } -> C1<int>; };

int main() {
    class A { int x; } a;
    a.x = 42;
}
```
It fails to compile as it should when I paste the preprocessed TU into godbolt (https://godbolt.org/z/-9KM6s), but when I run it against my locally-built clang-concepts it ICEs:
```
casey@EqualityComparable:~/repos/llvm/projects/libcxx$ ~/build/llvm/g8/bin/clang -std=c++2a -Xclang -fconcepts-ts ~/casey/Desktop/repro.cpp
clang-8.0: /home/casey/repos/llvm/tools/clang/include/clang/AST/TemplateBase.h:258: clang::QualType clang::TemplateArgument::getAsType() const: Assertion `getKind() == Type && "Unexpected kind"' failed.
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x33)[0x3dc5e11]
/home/casey/build/llvm/g8/bin/clang-8.0[0x3dc5ea4]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN4llvm3sys17RunSignalHandlersEv+0x99)[0x3dc4073]
/home/casey/build/llvm/g8/bin/clang-8.0[0x3dc567f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f5c6f9f1390]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f5c6e945428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f5c6e94702a]
/lib/x86_64-linux-gnu/libc.so.6(+0x2dbd7)[0x7f5c6e93dbd7]
/lib/x86_64-linux-gnu/libc.so.6(+0x2dc82)[0x7f5c6e93dc82]
/home/casey/build/llvm/g8/bin/clang-8.0[0x405b952]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang4Sema20matchTypeByDeductionEPNS_21TemplateParameterListENS_8QualTypeEPNS_4ExprE+0x261)[0x668b927]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang15ExprRequirement21ReturnTypeRequirement21calculateSatisfactionERNS_4SemaEPNS_4ExprE+0x27b)[0x5e6b855]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang15ExprRequirementC2ERNS_4SemaEPNS_4ExprEbNS_14SourceLocationENS0_21ReturnTypeRequirementE+0x1c2)[0x5e6af58]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang4Sema24ActOnCompoundRequirementEPNS_4ExprENS_14SourceLocationES3_RKNS_12CXXScopeSpecEPNS_9NamedDeclEPNS_11ConceptDeclENS_24TemplateArgumentListInfoERNS_10DeclaratorEj+0x437)[0x6307d85]
/home/casey/build/llvm/g8/bin/clang-8.0[0x5a82a56]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser23ParseRequiresExpressionEv+0xdd9)[0x5a838bb]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser19ParseCastExpressionEbbRbNS0_13TypeCastStateEb+0x3e08)[0x5a6b554]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser19ParseCastExpressionEbbNS0_13TypeCastStateEb+0x56)[0x5a674ee]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser25ParseConstraintExpressionEv+0x67)[0x5a65f7f]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser22ParseConceptDefinitionEjRKNS0_18ParsedTemplateInfoERNS_21ParsingDeclRAIIObjectERNS_14SourceLocationENS_15AccessSpecifierEPNS_13AttributeListE+0x181)[0x5accb53]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser40ParseTemplateDeclarationOrSpecializationEjRNS_14SourceLocationENS_15AccessSpecifierEPNS_13AttributeListE+0x58e)[0x5acbd82]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser36ParseDeclarationStartingWithTemplateEjRNS_14SourceLocationENS_15AccessSpecifierEPNS_13AttributeListE+0xe8)[0x5acb7c6]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser16ParseDeclarationEjRNS_14SourceLocationERNS0_25ParsedAttributesWithRangeE+0xee)[0x5a2743c]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser24ParseExternalDeclarationERNS0_25ParsedAttributesWithRangeEPNS_15ParsingDeclSpecE+0x903)[0x5a08861]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser17ParseTopLevelDeclERNS_9OpaquePtrINS_12DeclGroupRefEEE+0x353)[0x5a07f17]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang8ParseASTERNS_4SemaEbb+0x24f)[0x5a03f26]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang17ASTFrontendAction13ExecuteActionEv+0x143)[0x473d335]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang13CodeGenAction13ExecuteActionEv+0x492)[0x4c5a8be]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang14FrontendAction7ExecuteEv+0x96)[0x473cd78]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x53c)[0x46d9d3c]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x69c)[0x488e1f9]
/home/casey/build/llvm/g8/bin/clang-8.0(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x455)[0x1be56f9]
/home/casey/build/llvm/g8/bin/clang-8.0[0x1bdaa9f]
/home/casey/build/llvm/g8/bin/clang-8.0(main+0xaa5)[0x1bdb709]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f5c6e930830]
/home/casey/build/llvm/g8/bin/clang-8.0(_start+0x29)[0x1bd81e9]
Stack dump:
0.      Program arguments: /home/casey/build/llvm/g8/bin/clang-8.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name repro.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -resource-dir /home/casey/build/llvm/g8/lib/clang/6.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/backward -internal-isystem /usr/local/include -internal-isystem /home/casey/build/llvm/g8/lib/clang/6.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++2a -fdeprecated-macro -fdebug-compilation-dir /home/casey/repos/llvm/projects/libcxx -ferror-limit 19 -fmessage-length 120 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -fconcepts-ts -o /tmp/repro-882941.o -x c++ /home/casey/casey/Desktop/repro.cpp
1.      /home/casey/casey/Desktop/repro.cpp:5:42: current parser token ';'
clang-8.0: error: unable to execute command: Aborted (core dumped)
clang-8.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (git@github.com:/saarraz/clang-concepts 4709aa33d13e319e9d3c9b30fce8541a1d6939ff) (https://git.llvm.org/git/llvm.git 893a41656b527af1b00a1f9e5c8fcecfff62e4b6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/casey/build/llvm/g8/bin
clang-8.0: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-8.0: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-8.0: note: diagnostic msg: /tmp/repro-7bcf10.cpp
clang-8.0: note: diagnostic msg: /tmp/repro-7bcf10.sh
clang-8.0: note: diagnostic msg:

********************
```
Note that "/home/casey/casey/Desktop/repro.cpp:5:42: current parser token ';'" is the `;` in the *compound-requirement* `{ 42 } -> C1<int>;`. 

I suspect the issue is either a command-line difference vs. Godbolt, or (much scarier) an actual behavior difference in the compiler caused by building it with different tools - I'm using `g++-8 (Ubuntu 8.1.0-5ubuntu1~16.04) 8.1.0` on Ubuntu Xenial. My Undefined Behavior sense is tingling.

In any case, it's probably worth running down the problem.

**Comment by saarraz** [comment] 2018-11-18 22:43
I'm not getting a crash on my build either 🤔

**Comment by saarraz** [comment] 2018-11-18 22:45
Correction, tested with assertions turned on and I get the same thing, will check it out. (No UB, phew)

**Comment by saarraz** [comment] 2018-11-18 23:06
OK pushed something that should fix this, but it'll take me time to rebuild my debug build - can you check if the issue is resolved on your side?

**Comment by CaseyCarter** [comment] 2018-11-18 23:19
> can you check if the issue is resolved on your side?

Same result.

**Comment by CaseyCarter** [comment] 2018-11-19 00:43
> > can you check if the issue is resolved on your side?
> 
> Same result.

Sorry, I lied. It still asserts, but the assert is different:
```
casey@EqualityComparable:~/build/llvm/g8$ bin/clang -std=c++2a -Xclang -fconcepts-ts ~/casey/Desktop/repro.cpp
clang-8.0: /home/casey/repos/llvm/tools/clang/include/clang/AST/ExprCXX.h:4513: bool clang::ConceptSpecializationExpr::isSatisfied() const: Assertion `!isValueDependent() && "isSatisfied called on a dependent ConceptSpecializationExpr"' failed.
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x33)[0x3dc5e11]
/home/casey/build/llvm/g8/bin/clang-8.0[0x3dc5ea4]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN4llvm3sys17RunSignalHandlersEv+0x99)[0x3dc4073]
/home/casey/build/llvm/g8/bin/clang-8.0[0x3dc567f]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f47c27f1390]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f47c1745428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f47c174702a]
/lib/x86_64-linux-gnu/libc.so.6(+0x2dbd7)[0x7f47c173dbd7]
/lib/x86_64-linux-gnu/libc.so.6(+0x2dc82)[0x7f47c173dc82]
/home/casey/build/llvm/g8/bin/clang-8.0[0x447e2be]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang15ExprRequirement21ReturnTypeRequirement21calculateSatisfactionERNS_4SemaEPNS_4ExprE+0x40b)[0x5e6b9e5]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang15ExprRequirementC2ERNS_4SemaEPNS_4ExprEbNS_14SourceLocationENS0_21ReturnTypeRequirementE+0x1c2)[0x5e6af58]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang4Sema24ActOnCompoundRequirementEPNS_4ExprENS_14SourceLocationES3_RKNS_12CXXScopeSpecEPNS_9NamedDeclEPNS_11ConceptDeclENS_24TemplateArgumentListInfoERNS_10DeclaratorEj+0x437)[0x6307da3]
/home/casey/build/llvm/g8/bin/clang-8.0[0x5a82a56]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser23ParseRequiresExpressionEv+0xdd9)[0x5a838bb]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser19ParseCastExpressionEbbRbNS0_13TypeCastStateEb+0x3e08)[0x5a6b554]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser19ParseCastExpressionEbbNS0_13TypeCastStateEb+0x56)[0x5a674ee]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser25ParseConstraintExpressionEv+0x67)[0x5a65f7f]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser22ParseConceptDefinitionEjRKNS0_18ParsedTemplateInfoERNS_21ParsingDeclRAIIObjectERNS_14SourceLocationENS_15AccessSpecifierEPNS_13AttributeListE+0x181)[0x5accb53]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser40ParseTemplateDeclarationOrSpecializationEjRNS_14SourceLocationENS_15AccessSpecifierEPNS_13AttributeListE+0x58e)[0x5acbd82]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser36ParseDeclarationStartingWithTemplateEjRNS_14SourceLocationENS_15AccessSpecifierEPNS_13AttributeListE+0xe8)[0x5acb7c6]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser16ParseDeclarationEjRNS_14SourceLocationERNS0_25ParsedAttributesWithRangeE+0xee)[0x5a2743c]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser24ParseExternalDeclarationERNS0_25ParsedAttributesWithRangeEPNS_15ParsingDeclSpecE+0x903)[0x5a08861]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang6Parser17ParseTopLevelDeclERNS_9OpaquePtrINS_12DeclGroupRefEEE+0x353)[0x5a07f17]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang8ParseASTERNS_4SemaEbb+0x24f)[0x5a03f26]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang17ASTFrontendAction13ExecuteActionEv+0x143)[0x473d335]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang13CodeGenAction13ExecuteActionEv+0x492)[0x4c5a8be]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang14FrontendAction7ExecuteEv+0x96)[0x473cd78]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x53c)[0x46d9d3c]
/home/casey/build/llvm/g8/bin/clang-8.0(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x69c)[0x488e1f9]
/home/casey/build/llvm/g8/bin/clang-8.0(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x455)[0x1be56f9]
/home/casey/build/llvm/g8/bin/clang-8.0[0x1bdaa9f]
/home/casey/build/llvm/g8/bin/clang-8.0(main+0xaa5)[0x1bdb709]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f47c1730830]
/home/casey/build/llvm/g8/bin/clang-8.0(_start+0x29)[0x1bd81e9]
Stack dump:
0.      Program arguments: /home/casey/build/llvm/g8/bin/clang-8.0 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -main-file-name repro.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -resource-dir /home/casey/build/llvm/g8/lib/clang/6.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/backward -internal-isystem /usr/local/include -internal-isystem /home/casey/build/llvm/g8/lib/clang/6.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++2a -fdeprecated-macro -fdebug-compilation-dir /home/casey/build/llvm/g8 -ferror-limit 19 -fmessage-length 120 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -fconcepts-ts -o /tmp/repro-72abcd.o -x c++ /home/casey/casey/Desktop/repro.cpp
1.      /home/casey/casey/Desktop/repro.cpp:5:42: current parser token ';'
clang-8.0: error: unable to execute command: Aborted (core dumped)
clang-8.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (git@github.com:/saarraz/clang-concepts cbb181984404402efde836d7ee31e8c31d283233) (https://git.llvm.org/git/llvm.git 893a41656b527af1b00a1f9e5c8fcecfff62e4b6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/casey/build/llvm/g8/bin
clang-8.0: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-8.0: note: diagnostic msg:
********************
```

**Comment by saarraz** [comment] 2018-11-19 22:26
Fixed now.

**Closed as completed by saarraz** 2018-11-19 22:26 UTC
