### ISSUE TITLE
Clang treating a _simple-requirement_ that names a deleted function as satisfied

### ISSUE THREAD

**Issue by cjdb** [saarraz/clang-concepts-old#22] opened 2018-10-28 23:12 UTC
This was first identified while trying to implement [P0896](https://wg21.link/p0896) `ranges::swap`. The problem with `ranges::swap` is that the `noexcept` specifier is trying to evaluate something that is deemed inappropriate by the requirements.

```cpp
#define NOEXCEPT_RETURN(...) noexcept(noexcept(__VA_ARGS__)) { return __VA_ARGS__; }

namespace cjdb::ranges {
   namespace detail {
      inline namespace swap {
          template<class T, class U>
          void swap(T&&, U&&) = delete;
   
          template<class T, class U, decltype(sizeof(0)) N>
          void swap(T(&)[N], U(&)[N]) = delete;
   
          template<class T, class U>
          concept is_customised = requires(T&& t, U&& u) {
              (void)swap(static_cast<T&&>(t), static_cast<U&&>(u));
          };
   
          struct swap_fn {
              template<class T, class U>
              requires is_customised<T, U>
              constexpr void operator()(T&& t, U&& u) const
              NOEXCEPT_RETURN(
                  (void)swap(static_cast<T&&>(t), static_cast<U&&>(u))
              )
          };
      }
   }

   constexpr auto swap = detail::swap::swap_fn{};
}

template<class T> T declval();

static_assert(noexcept(cjdb::ranges::swap(declval<int&>(), declval<int&>())));
```

Link: https://godbolt.org/z/b1aV4K

@CaseyCarter has been able to further reduce it to:

```cpp
#if __cpp_concepts > 201507L
#define CONCEPT concept
#else
#define CONCEPT concept bool
#endif

template<class T> void f(T) = delete;

template<class T>
CONCEPT C = requires(T t) { f(t); };

struct S1 {};
struct S2 { friend void f(S2); };

static_assert(!C<int>);
static_assert(!C<S1>);
static_assert(C<S2>);
```

Link: https://godbolt.org/z/d-DWG7

and

```cpp
template<class T> void f(T) = delete;

template<class T>
concept C = requires(T t) { f(t); };

static_assert(!C<int>);
```

Link: https://godbolt.org/z/oiBjkp

**Comment by CaseyCarter** [comment] 2018-10-28 23:42
> The problem with ranges::swap is that the `noexcept` specifier is trying to evaluate something that is deemed inappropriate by the requirements.

The root cause is that clang incorrectly treats an expression constraint that references a deleted function as satisfied. The fact that it notices the ill-formed `noexcept` specifier is a symptom. The function template specialization with the ill-formed exception specifier should never be instantiated since its associated constraints aren't satisfied.

**Comment by saarraz** [comment] 2018-11-05 20:57
Fixed in latest commit.

**Closed as completed by saarraz** 2018-11-05 20:57 UTC
