### ISSUE TITLE
Possible subsumption bug

### ISSUE THREAD

**Issue by Quuxplusone** [saarraz/clang-concepts-old#38] opened 2018-11-28 00:03 UTC
I'm not sure if this is a bug or not, but it's certainly confusing as heck.
https://godbolt.org/z/DW4vWs

Defining `FOO` makes this program no longer compile.

```
template<class T>
concept Priority0 = 0==0;

template<class T>
concept Priority1 = 1==1 && Priority0<T>;

extern "C" void PRI1();
extern "C" void PRI0();

template<Priority0 T>
#ifdef FOO
 requires Priority0<void>
#endif
void foo(T t) {
    PRI0();
}

template<Priority1 T>
#ifdef FOO
 requires Priority1<void>
#endif
void foo(T t) {
    PRI1();
}

int main()
{
    foo(42);
}
```

Surely if `Priority1<T> [with T=int]`
subsumes `Priority0<T> [with T=int]`, then
`conjunction-of {Priority1<T> [with T=int], Priority1<void>}` should subsume
`conjunction-of {Priority0<T> [with T=int], Priority0<void>}`, right?

**Comment by saarraz** [comment] 2019-01-28 22:16
Fixed in latest commit (this was a regression caused by a previous fix).

**Closed as completed by saarraz** 2019-01-28 22:16 UTC
